unstable_features = true
comment_width = 72
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 90
format_strings = true
imports_indent = "Visual"
match_block_trailing_comma = true
max_width = 90
imports_granularity = "Crate"
overflow_delimited_expr = false
reorder_impl_items = true
struct_field_align_threshold = 20
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
